# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
      - job: MavenPackageAndPublishArtifacts
        steps:
        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            goals: package
            mavenPomFile: 'pom.xml'
            jdkVersionOption: '1.11'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/target/*.?(war|jar)'
            artifact: 'drop'
            publishLocation: 'pipeline'
  - stage: Test
    dependsOn:
      - Build
    jobs:
    - job: Test
      steps:
      - task: Maven@3
        inputs:
          goals: test
          mavenPomFile: 'pom.xml'
          jdkVersionOption: '1.11'
  - stage: Deploy_staging
    dependsOn:
      - Build
      - Test
    jobs:
    - deployment: Deploy_staging
      environment: testing
      strategy:
        runOnce:
          deploy:   
            steps:
                - task: Docker@2
                  inputs:
                    containerRegistry: 'azure Code cafe'
                    repository: 'azurePipelinesCodeCafe'
                    command: 'buildAndPush'
                    Dockerfile: '**/Dockerfile'
                    tags: |
                      azurepipelinecodecafe
  - stage: Deploy_production
    dependsOn:
      - Build
      - Test
      - Deploy_staging
    jobs:
    - deployment: Deploy_Production
      condition: eq(variables['Build.SourceBranchName'], 'master')
      environment: production
      strategy:
        runOnce:
          deploy:   
            steps:
                - task: Docker@2
                  inputs:
                    containerRegistry: 'azure Code cafe'
                    repository: 'azurePipelinesCodeCafe-production'
                    command: 'buildAndPush'
                    Dockerfile: '**/Dockerfile'
                    tags: |
                      azurepipelinecodecafe-production